In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dn=pd.read_csv('C:/Users/SONY/Desktop/titanic_data.csv')
dn.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [3]:
dn.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis=1,inplace=True)
dn.head(3)

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250

In [4]:
X=dn.drop(['Survived'],axis=1)
y=dn['Survived']

In [5]:
dummies=pd.get_dummies(X.Sex)
dummies.head(3)

female  male
0       0     1
1       1     0
2       1     0

In [6]:
X=pd.concat([X,dummies],axis=1)
X.head(3)

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0

In [7]:
X.drop('Sex',axis=1,inplace=True)
X.head(3)

Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0

In [8]:
X.columns[X.isna().any()]

Index(['Age'], dtype='object')

In [9]:
X.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [10]:
X.Age=X.Age.fillna(X.Age.mean())
X.head(3)

Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0

In [11]:
from sklearn.model_selection import train_test_split

In [18]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [13]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((712, 5), (179, 5), (712,), (179,))

In [19]:
from sklearn.naive_bayes import GaussianNB

In [20]:
Model=GaussianNB()

In [21]:
Model.fit(X_train,y_train)

GaussianNB()

In [22]:
Model.score(X_test,y_test)

0.776536312849162

In [23]:
X_test[:10]

Pclass        Age     Fare  female  male
862       1  48.000000  25.9292       1     0
223       3  29.699118   7.8958       0     1
84        2  17.000000  10.5000       1     0
680       3  29.699118   8.1375       1     0
535       2   7.000000  26.2500       1     0
623       3  21.000000   7.8542       0     1
148       2  36.500000  26.0000       0     1
3         1  35.000000  53.1000       1     0
34        1  28.000000  82.1708       0     1
241       3  29.699118  15.5000       1     0

In [24]:
y_test[:10]

862    1
223    0
84     1
680    0
535    1
623    0
148    0
3      1
34     0
241    1
Name: Survived, dtype: int64

In [32]:
Pre=Model.predict(X_test)
Pre

array([1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1], dtype=int64)

In [33]:
Model.predict_proba(X_test[:10])

array([[0.00641471, 0.99358529],
       [0.99055747, 0.00944253],
       [0.02162335, 0.97837665],
       [0.06341096, 0.93658904],
       [0.01375034, 0.98624966],
       [0.98907735, 0.01092265],
       [0.97689823, 0.02310177],
       [0.00437148, 0.99562852],
       [0.69151423, 0.30848577],
       [0.06308945, 0.93691055]])

In [34]:
from sklearn.metrics import classification_report

In [35]:
classification_report(y_test,Pre)

'              precision    recall  f1-score   support\n\n           0       0.79      0.84      0.82       106\n           1       0.75      0.68      0.71        73\n\n    accuracy                           0.78       179\n   macro avg       0.77      0.76      0.77       179\nweighted avg       0.77      0.78      0.77       179\n'

In [36]:
from sklearn.metrics import confusion_matrix

In [37]:
confusion_matrix(y_test,Pre)

array([[89, 17],
       [23, 50]], dtype=int64)

In [39]:
from sklearn.metrics import accuracy_score

In [40]:
accuracy_score(y_test,Pre)*100

77.6536312849162

In [38]:
from sklearn.model_selection import cross_val_score

In [42]:
cross_val_score(GaussianNB(),X,y)

array([0.79329609, 0.80337079, 0.78089888, 0.74719101, 0.79775281])